trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'