trigger:
- EMILIANO2

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Use .NET SDK 8.x'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'