# Configuración del trigger: se ejecutará cuando haya cambios en la rama master
trigger:
  branches:
    include:
      - master  # o el nombre de tu rama principal

# Configuración de la máquina virtual que ejecutará el pipeline
pool:
  vmImage: 'windows-latest'  # o la imagen que prefieras

# Definición de variables que pueden ser utilizadas en otros pasos del pipeline
variables:
  buildConfiguration: 'Release'

# Pasos del pipeline
steps:
  # Paso 1: Restaurar los paquetes NuGet necesarios para el proyecto
  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  # Paso 2: Configurar MSBuild para proyectos .NET Framework
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

  # Paso 3: Ejecutar las pruebas del proyecto (ajusta según tu configuración)
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'