trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: RunTests
  displayName: 'Run Tests'
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - script: dotnet build --configuration Debug
    displayName: 'Build Solution'

  - task: VSTest@2
    displayName: 'Run Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\Debug\*_TS.dll
      searchFolder: '$(System.DefaultWorkingDirectory)'
      codeCoverageEnabled: true
      platform: 'Any CPU'
      configuration: 'Debug'
