trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: RunTests
  displayName: 'Run Tests'
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore
    displayName: 'Restore NuGet Packages'

  - script: dotnet build --configuration $(BuildConfiguration)
    displayName: 'Build Solution'

  - task: VSTest@2
    displayName: 'Run Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\$(BuildConfiguration)\*_TS.dll
      searchFolder: '$(System.DefaultWorkingDirectory)'
      codeCoverageEnabled: true
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'